#/mycommands/addPhysics emstandard_opt4
/random/setSeeds 13436425 84743374
/run/setCut 0.01 mm
/run/initialize
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#/score/colorMap/setMinMax ! 0.01 0.99


/gps/particle ion
/gps/ion 44 106 0 0.0
/gps/energy 0. keV
/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/radius 12.1 mm
/gps/pos/centre 0. 0. 0.1 mm
/gps/ang/type iso
/gps/pos/confine Target_silver_PV


/run/beamOn 100
